from __future__ import annotations


STOCK_UNIVERSE: dict[str, str] = {
    # =========== GOLD / PRECIOUS METALS ===========
    "XAUUSD": "Gold Spot (XAU/USD)",
    "XAGUSD": "Silver Spot (XAG/USD)",
    "XPTUSD": "Platinum Spot (XPT/USD)",
    "XPDUSD": "Palladium Spot (XPD/USD)",
    "GC=F": "Gold Futures (COMEX)",
    "SI=F": "Silver Futures (COMEX)",
    "PL=F": "Platinum Futures (COMEX)",
    "PA=F": "Palladium Futures (COMEX)",
    "GLD": "SPDR Gold Shares ETF",
    "IAU": "iShares Gold Trust ETF",
    "SGOL": "abrdn Physical Gold Shares ETF",
    "GLDM": "SPDR Gold MiniShares ETF",
    "BAR": "GraniteShares Gold Trust ETF",
    "SLV": "iShares Silver Trust ETF",
    "SIVR": "abrdn Physical Silver ETF",
    "PPLT": "abrdn Physical Platinum ETF",
    "PALL": "abrdn Physical Palladium ETF",
    "DBC": "Invesco DB Commodity Index Tracking Fund",
    "PDBC": "Invesco Optimum Yield Diversified Commodity Strategy",
    "BCI": "Invesco Bloomberg Commodity ETF",
    "USCI": "United States Commodity Index Fund",
    "COPX": "Global X Copper Miners ETF",
    "GDX": "VanEck Gold Miners ETF",
    "GDXJ": "VanEck Junior Gold Miners ETF",
    "SIL": "Global X Silver Miners ETF",
    "SILJ": "ETFMG Prime Junior Silver Miners ETF",
    "PPLT": "abrdn Physical Platinum Shares ETF",
    "PALL": "abrdn Physical Palladium Shares ETF",
    "RING": "iShares MSCI Global Gold Miners ETF",
    "GOEX": "Global X Gold Explorers ETF",
    "GLDX": "U.S. Global GO GOLD and Precious Metal Miners ETF",
    "MCAF": "Monte Carlo Alternative Fund",
    "MUX": "McEwen Mining",
    "NEM": "Newmont Corporation",
    "GOLD": "Barrick Gold",
    "AEM": "Agnico Eagle Mines",
    "KGC": "Kinross Gold",
    "AU": "AngloGold Ashanti",
    "HMY": "Harmony Gold Mining",
    "GFI": "Gold Fields",
    "AUY": "Yamana Gold",
    "EGO": "Eldorado Gold",
    "KL": "Kirkland Lake Gold",
    "AGI": "Alamos Gold",
    "MAG": "MAG Silver",
    "PAAS": "Pan American Silver",
    "CDE": "Coeur Mining",
    "HL": "Hecla Mining",
    "FNV": "Franco-Nevada",
    "WPM": "Wheaton Precious Metals",
    "RGLD": "Royal Gold",
    "SAND": "Sandstorm Gold",
    "OR": "Osisko Gold Royalties",
    "MTA": "Metalla Royalty & Streaming",
    "SAND": "Sandstorm Gold",
    "SIL": "Global X Silver Miners ETF",
    # =========== CRYPTO ===========
    "BTC-USD": "Bitcoin",
    "ETH-USD": "Ethereum",
    "SOL-USD": "Solana",
    "BNB-USD": "Binance Coin",
    "XRP-USD": "XRP",
    "ADA-USD": "Cardano",
    "DOGE-USD": "Dogecoin",
    "AVAX-USD": "Avalanche",
    "DOT-USD": "Polkadot",
    "MATIC-USD": "Polygon",
    "LINK-USD": "Chainlink",
    "UNI-USD": "Uniswap",
    "LTC-USD": "Litecoin",
    "BCH-USD": "Bitcoin Cash",
    # =========== US STOCKS ===========
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft",
    "GOOGL": "Alphabet",
    "AMZN": "Amazon",
    "NVDA": "NVIDIA",
    "META": "Meta Platforms",
    "TSLA": "Tesla",
    "NFLX": "Netflix",
    "AMD": "AMD",
    "INTC": "Intel",
    "CRM": "Salesforce",
    "ORCL": "Oracle",
    "ADBE": "Adobe",
    "QCOM": "Qualcomm",
    "AVGO": "Broadcom",
    "JPM": "JPMorgan Chase",
    "BAC": "Bank of America",
    "GS": "Goldman Sachs",
    "MS": "Morgan Stanley",
    "BRK-B": "Berkshire Hathaway",
    "V": "Visa",
    "MA": "Mastercard",
    "JPM": "JPMorgan Chase",
    "BAC": "Bank of America",
    "GS": "Goldman Sachs",
    "MS": "Morgan Stanley",
    "BRK-B": "Berkshire Hathaway",
    "V": "Visa",
    "MA": "Mastercard",
    "JNJ": "Johnson & Johnson",
    "PFE": "Pfizer",
    "UNH": "UnitedHealth",
    "LLY": "Eli Lilly",
    "ABBV": "AbbVie",
    "WMT": "Walmart",
    "MCD": "McDonald's",
    "KO": "Coca-Cola",
    "PEP": "PepsiCo",
    "NKE": "Nike",
    "RELIANCE.NS": "Reliance Industries",
    "TCS.NS": "TCS",
    "INFY.NS": "Infosys",
    "HDFCBANK.NS": "HDFC Bank",
    "ICICIBANK.NS": "ICICI Bank",
    "SBIN.NS": "SBI",
    "WIPRO.NS": "Wipro",
    "HINDUNILVR.NS": "HUL",
    "BAJFINANCE.NS": "Bajaj Finance",
    "MARUTI.NS": "Maruti Suzuki",
    "TITAN.NS": "Titan",
    "ADANIENT.NS": "Adani Enterprises",
    "LT.NS": "L&T",
    "SUNPHARMA.NS": "Sun Pharma",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "ASIANPAINT.NS": "Asian Paints",
    "NESTLEIND.NS": "Nestle India",
    "ONGC.NS": "ONGC",
    "POWERGRID.NS": "Power Grid",
    "TATAMOTORS.NS": "Tata Motors",
    "BTC-USD": "Bitcoin",
    "ETH-USD": "Ethereum",
    "SOL-USD": "Solana",
    "BNB-USD": "Binance Coin",
    "XRP-USD": "XRP",
    "ADA-USD": "Cardano",
    "SPY": "S&P 500 ETF",
    "QQQ": "NASDAQ ETF",
    "IWM": "Russell 2000 ETF",
    "GLD": "Gold ETF",
    "SLV": "Silver ETF",
    "^GSPC": "S&P 500",
    "^IXIC": "NASDAQ",
    "^DJI": "Dow Jones",
    "^NSEI": "Nifty 50",
    "^BSESN": "BSE Sensex",
}

SECTOR_HINTS: dict[str, str] = {
    # =========== GOLD / PRECIOUS METALS ===========
    "XAUUSD": "Precious Metals",
    "XAGUSD": "Precious Metals",
    "XPTUSD": "Precious Metals",
    "XPDUSD": "Precious Metals",
    "GC=F": "Precious Metals",
    "SI=F": "Precious Metals",
    "PL=F": "Precious Metals",
    "PA=F": "Precious Metals",
    "GLD": "Precious Metals",
    "IAU": "Precious Metals",
    "SGOL": "Precious Metals",
    "GLDM": "Precious Metals",
    "BAR": "Precious Metals",
    "SLV": "Precious Metals",
    "SIVR": "Precious Metals",
    "PPLT": "Precious Metals",
    "PALL": "Precious Metals",
    "DBC": "Commodities",
    "PDBC": "Commodities",
    "BCI": "Commodities",
    "USCI": "Commodities",
    "COPX": "Materials",
    "GDX": "Materials",
    "GDXJ": "Materials",
    "SIL": "Materials",
    "SILJ": "Materials",
    "PPLT": "Precious Metals",
    "PALL": "Precious Metals",
    "RING": "Materials",
    "GOEX": "Materials",
    "GLDX": "Materials",
    "MCAF": "Financial Services",
    "MUX": "Materials",
    "NEM": "Materials",
    "GOLD": "Materials",
    "AEM": "Materials",
    "KGC": "Materials",
    "AU": "Materials",
    "HMY": "Materials",
    "GFI": "Materials",
    "AUY": "Materials",
    "EGO": "Materials",
    "KL": "Materials",
    "AGI": "Materials",
    "MAG": "Materials",
    "PAAS": "Materials",
    "CDE": "Materials",
    "HL": "Materials",
    "FNV": "Financial Services",
    "WPM": "Financial Services",
    "RGLD": "Financial Services",
    "SAND": "Financial Services",
    "OR": "Financial Services",
    "MTA": "Financial Services",
    "SIL": "Materials",
    # =========== CRYPTO ===========
    "BTC-USD": "Crypto",
    "ETH-USD": "Crypto",
    "SOL-USD": "Crypto",
    "BNB-USD": "Crypto",
    "XRP-USD": "Crypto",
    "ADA-USD": "Crypto",
    "DOGE-USD": "Crypto",
    "AVAX-USD": "Crypto",
    "DOT-USD": "Crypto",
    "MATIC-USD": "Crypto",
    "LINK-USD": "Crypto",
    "UNI-USD": "Crypto",
    "LTC-USD": "Crypto",
    "BCH-USD": "Crypto",
    # =========== US STOCKS ===========
    "AAPL": "Technology",
    "MSFT": "Technology",
    "GOOGL": "Communication Services",
    "AMZN": "Consumer Cyclical",
    "NVDA": "Technology",
    "META": "Communication Services",
    "TSLA": "Consumer Cyclical",
    "JPM": "Financial Services",
    "BAC": "Financial Services",
    "GS": "Financial Services",
    "MS": "Financial Services",
    "BRK-B": "Financial Services",
    "V": "Financial Services",
    "MA": "Financial Services",
    "JPM": "Financial Services",
    "BAC": "Financial Services",
    "GS": "Financial Services",
    "MS": "Financial Services",
    "BRK-B": "Financial Services",
    "V": "Financial Services",
    "MA": "Financial Services",
    "JNJ": "Healthcare",
    "PFE": "Healthcare",
    "UNH": "Healthcare",
    "LLY": "Healthcare",
    "ABBV": "Healthcare",
    "WMT": "Consumer Defensive",
    "MCD": "Consumer Cyclical",
    "KO": "Consumer Defensive",
    "PEP": "Consumer Defensive",
    "NKE": "Consumer Cyclical",
    "RELIANCE.NS": "Energy",
    "TCS.NS": "Technology",
    "INFY.NS": "Technology",
    "HDFCBANK.NS": "Financial Services",
    "ICICIBANK.NS": "Financial Services",
    "SBIN.NS": "Financial Services",
    "WIPRO.NS": "Technology",
    "HINDUNILVR.NS": "Consumer Defensive",
    "BAJFINANCE.NS": "Financial Services",
    "MARUTI.NS": "Consumer Cyclical",
    "TITAN.NS": "Consumer Cyclical",
    "ADANIENT.NS": "Materials",
    "LT.NS": "Industrials",
    "SUNPHARMA.NS": "Healthcare",
    "ULTRACEMCO.NS": "Materials",
    "ASIANPAINT.NS": "Materials",
    "NESTLEIND.NS": "Consumer Defensive",
    "ONGC.NS": "Energy",
    "POWERGRID.NS": "Utilities",
    "TATAMOTORS.NS": "Consumer Cyclical",
    "BTC-USD": "Crypto",
    "ETH-USD": "Crypto",
    "SOL-USD": "Crypto",
    "BNB-USD": "Crypto",
    "XRP-USD": "Crypto",
    "ADA-USD": "Crypto",
    "SPY": "ETF",
    "QQQ": "ETF",
    "IWM": "ETF",
    "GLD": "ETF",
    "SLV": "ETF",
    "^GSPC": "Index",
    "^IXIC": "Index",
    "^DJI": "Index",
    "^NSEI": "Index",
    "^BSESN": "Index",
}


def infer_exchange(symbol: str) -> str:
    # =========== GOLD / PRECIOUS METALS ===========
    gold_symbols = {
        "XAUUSD", "XAGUSD", "XPTUSD", "XPDUSD",
        "GC=F", "SI=F", "PL=F", "PA=F",
        "GLD", "IAU", "SGOL", "GLDM", "BAR",
        "SLV", "SIVR", "PPLT", "PALL",
        "DBC", "PDBC", "BCI", "USCI",
        "COPX", "GDX", "GDXJ", "SIL", "SILJ",
        "PPLT", "PALL", "RING", "GOEX", "GLDX",
        "MCAF", "MUX", "NEM", "GOLD", "AEM",
        "KGC", "AU", "HMY", "GFI", "AUY",
        "EGO", "KL", "AGI", "MAG", "PAAS",
        "CDE", "HL", "FNV", "WPM", "RGLD",
        "SAND", "OR", "MTA", "SIL",
    }
    if symbol in gold_symbols:
        return "COMEX" if symbol.endswith("=F") else "OTC"
    if symbol.endswith(".NS"):
        return "NSE"
    if symbol.endswith(".BO"):
        return "BSE"
    if symbol.endswith("-USD"):
        return "Crypto"
    if symbol.startswith("^"):
        return "Index"
    return "US"


def infer_asset_type(symbol: str) -> str:
    gold_symbols = {
        "XAUUSD", "XAGUSD", "XPTUSD", "XPDUSD",
        "GC=F", "SI=F", "PL=F", "PA=F",
        "GLD", "IAU", "SGOL", "GLDM", "BAR",
        "SLV", "SIVR", "PPLT", "PALL",
        "DBC", "PDBC", "BCI", "USCI",
        "COPX", "GDX", "GDXJ", "SIL", "SILJ",
        "PPLT", "PALL", "RING", "GOEX", "GLDX",
        "MCAF", "MUX", "NEM", "GOLD", "AEM",
        "KGC", "AU", "HMY", "GFI", "AUY",
        "EGO", "KL", "AGI", "MAG", "PAAS",
        "CDE", "HL", "FNV", "WPM", "RGLD",
        "SAND", "OR", "MTA", "SIL",
    }
    if symbol in gold_symbols:
        if symbol.endswith("=F"):
            return "future"
        if symbol in {"GLD", "IAU", "SGOL", "GLDM", "BAR", "SLV", "SIVR", "PPLT", "PALL",
                       "DBC", "PDBC", "BCI", "USCI", "COPX", "GDX", "GDXJ", "SIL", "SILJ",
                       "PPLT", "PALL", "RING", "GOEX", "GLDX", "MCAF", "MUX", "NEM", "GOLD",
                       "AEM", "KGC", "AU", "HMY", "GFI", "AUY", "EGO", "KL", "AGI", "MAG",
                       "PAAS", "CDE", "HL", "FNV", "WPM", "RGLD", "SAND", "OR", "MTA", "SIL"}:
            return "etf"
        if symbol in {"NEM", "GOLD", "AEM", "KGC", "AU", "HMY", "GFI", "AUY", "EGO", "KL",
                       "AGI", "MAG", "PAAS", "CDE", "HL", "FNV", "WPM", "RGLD", "SAND",
                       "OR", "MTA"}:
            return "stock"
        if symbol in {"FNV", "WPM", "RGLD", "SAND", "OR", "MTA"}:
            return "royalty"
        return "commodity"
    if symbol.endswith("-USD"):
        return "crypto"
    if symbol.startswith("^"):
        return "index"
    if symbol in {"SPY", "QQQ", "IWM", "GLD", "SLV"}:
        return "etf"
    return "stock"
